from enum import Enum
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field, validator
from datetime import datetime
import uuid

class InstrumentType(str, Enum):
    FOREX = "FOREX"
    CRYPTO = "CRYPTO"
    METALS = "METALS"
    INDICES_NY = "INDICES_NY"
    INDICES_B3 = "INDICES_B3"
    INDICES_EU = "INDICES_EU"
    STOCKS_US = "STOCKS_US"
    STOCKS_BR = "STOCKS_BR"
    STOCKS_EU = "STOCKS_EU"
    COMMODITIES_AGRI = "COMMODITIES_AGRI"
    COMMODITIES_ENERGY = "COMMODITIES_ENERGY"
    UNKNOWN = "UNKNOWN"

class InstrumentProfile(BaseModel):
    """Defines risk and behavior rules for a specific instrument type."""
    type: InstrumentType
    max_risk_per_trade_pct: float = 0.01  # 1%
    max_daily_dd_pct: float = 0.05       # 5%
    spread_max_points: int = 50
    slippage_buffer_points: int = 10
    min_score_to_trade: float = 60.0
    active: bool = True

class RiskConfig(BaseModel):
    hard_risk_cap_money: float = 50.0
    max_trades_open: int = 5
    max_trades_per_asset: int = 1
    max_daily_dd_pct: float = 0.05
    news_filter_active: bool = True
    spread_guard_active: bool = True
    max_lot_size: float = 0.01
    global_max_spread_points: int = 500
    global_max_daily_loss_currency: float = -50.0
    profiles: Dict[str, InstrumentProfile] = Field(default_factory=dict)

class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"

class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"

class OrderStatus(str, Enum):
    CREATED = "CREATED"
    PENDING = "PENDING"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCELED = "CANCELED"
    FAILED = "FAILED"

class TradeStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CLOSED_PARTIAL = "CLOSED_PARTIAL"

class Severity(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

# --- Value Objects & Entities ---

STRATEGY_MAGIC_MAP = {
    "SmartMoney": 3001,
    "TrendFollowing": 3002,
    "MeanReversion": 3003,
    "VolatilityBreakout": 3004,
    "OrderFlowScalping": 3005,
    "Unknown": 9999
}

def get_magic_for_strategy(strategy_name: str) -> int:
    return STRATEGY_MAGIC_MAP.get(strategy_name, 9999)

def get_strategy_for_magic(magic: int) -> str:
    reverse_map = {v: k for k, v in STRATEGY_MAGIC_MAP.items()}
    return reverse_map.get(magic, "Unknown")

def get_asset_class(symbol: str) -> InstrumentType:
    sym_upper = symbol.upper()
    if "BTC" in sym_upper or "ETH" in sym_upper or "SOL" in sym_upper:
        return InstrumentType.CRYPTO
    elif any(k in sym_upper for k in ["US30", "USA30", "US100", "NAS", "SPX", "US500", "USTEC"]):
        return InstrumentType.INDICES_NY
    elif any(k in sym_upper for k in ["WIN", "IND"]):
        return InstrumentType.INDICES_B3
    elif any(k in sym_upper for k in ["GER40", "UK100", "DE30", "FRA40", "HK50"]):
        return InstrumentType.INDICES_EU
    elif any(k in sym_upper for k in ["XAU", "XAG", "GOLD", "SILVER", "PLAT", "PALL"]):
        return InstrumentType.METALS
    elif any(k in sym_upper for k in ["CORN", "SOY", "SUGAR", "WHEAT"]):
        return InstrumentType.COMMODITIES_AGRI
    elif any(k in sym_upper for k in ["OIL", "WTI", "BRENT", "NATGAS", "GAS"]):
        return InstrumentType.COMMODITIES_ENERGY
    elif any(char.isdigit() for char in sym_upper) and len(sym_upper) >= 5:
        # Heuristic for B3 Stocks (e.g. PETR4, VALE3)
        return InstrumentType.STOCKS_BR
    elif len(sym_upper.replace("-T", "").replace(".T", "")) <= 4:
        # Heuristic for US Stocks (e.g. AAPL, TSLA)
        return InstrumentType.STOCKS_US
    else:
        return InstrumentType.FOREX

class Signal(BaseModel):
    """Raw signal generated by the Scanner."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    symbol: str
    direction: OrderSide
    score: float
    strategy_name: str
    metadata: Dict[str, Any] = {}
    
    class Config:
        frozen = True

class DraftOrder(BaseModel):
    """An intention to trade, produced by Arbiter, pending Risk Approval."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    signal_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    symbol: str
    side: OrderSide
    order_type: OrderType = OrderType.MARKET
    proposed_entry: float
    proposed_sl: Optional[float]
    proposed_tp: Optional[float]
    raw_volume: float = 0.01
    intent_id: str # Idempotency Key
    strategy_name: str = "Unknown"
    market_context: Optional[dict] = None

class RiskSnapshot(BaseModel):
    """Audit trail of risk calculations at the moment of approval."""
    equity: float
    balance: float
    risk_pct: float
    money_risk: float
    worst_case_loss: float
    hard_cap_approved: bool
    daily_dd_pct: float
    exposure_total: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)

class Order(BaseModel):
    """Approved order ready for execution."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    draft_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    symbol: str
    side: OrderSide
    volume: float
    sl: Optional[float]
    tp: Optional[float]
    magic_number: int
    comment: str
    intent_id: str
    strategy_name: str = "Unknown"
    risk_snapshot: Optional[RiskSnapshot] = None
    status: OrderStatus = OrderStatus.CREATED
    broker_ticket: Optional[int] = None
    execution_time: Optional[datetime] = None
    error_message: Optional[str] = None
    market_context: Optional[dict] = None

class Trade(BaseModel):
    """A realized position in the market."""
    ticket: int
    symbol: str
    side: OrderSide
    volume: float
    open_price: float
    open_time: datetime
    sl: Optional[float]
    tp: Optional[float]
    close_price: float = 0.0
    close_time: Optional[datetime] = None
    profit: float = 0.0
    commission: float = 0.0
    swap: float = 0.0
    status: TradeStatus = TradeStatus.OPEN
    magic: int
    comment: str = ""
    strategy_name: str = "Unknown"
    asset_class: str = "UNKNOWN"
    market_context: Optional[dict] = None
    # === Analytics Fields ===
    reason_code: Optional[str] = None          # Motivo da estratégia (ex: BREAKOUT_UP, SMC_AVOID_RANGE)
    score_signal: Optional[float] = None       # Score bruto gerado pela estratégia
    break_even_activated: bool = False         # True se Break-Even foi acionado neste trade
    trailing_stop_activated: bool = False      # True se Trailing Stop foi acionado

    @property
    def duration_seconds(self) -> float:
        end = self.close_time or datetime.utcnow()
        return (end - self.open_time).total_seconds()

class AccountInfo(BaseModel):
    """Snapshot of account state."""
    login: int
    balance: float
    equity: float
    profit: float
    margin: float
    margin_free: float
    margin_level: float
    currency: str
    server: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
