"""initial_schema

Revision ID: 00098c0f50c9
Revises: 
Create Date: 2026-03-10 16:30:09.617541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00098c0f50c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('component', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('ticket', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=20), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('magic', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('market_context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ticket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
